development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: imsnew
  pool: 5
  username: vasistha
  password: vasistha
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: imsnew
  pool: 5
  username: vasistha
  password: vasistha
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: imsnew
  pool: 5
  username: vasistha
  password: vasistha
  host: localhost
